Milestone-Mobile version
eudondian/Portfolio pull request #1
Opened 2022-05-27 13:44 UTC by eudondian

I added the mobile version header and Readme.md file

2022-05-27 16:44 UTC, ishimwezachee requested changes
Hi @eudondian  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Ishimwe Zachee  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-05-27 16:44 UTC, ishimwezachee commented on index.html
> +    </Section>
- [ ]  Your Toolbar container section should be `header`. Just replace 'section' with 'header'. This will make your code look very well structured.

2022-05-27 16:44 UTC, ishimwezachee commented on index.html
> +            <h3>My Logo</h3>
- [ ] You should put your logo in the anchor tag. (a tag), for your site to be more professional.

2022-05-27 16:44 UTC, ishimwezachee commented on index.html
> +
- [ ] You should list icons using 'ul tag to group them and li per icon; each icon has  a link (a tag)

2022-05-27 16:44 UTC, ishimwezachee commented on index.html
> +</section>
- [ ]  Your design should look much similar to the design from provided Figma design.  Adjust your font size, family, and weight referring to the fonts provided from Figma design. 

Your design | Figma design
--- | ---
![image](https://user-images.githubusercontent.com/43877689/170741422-1f119191-497f-4b18-a78f-51287b809dc9.png) | ![image](https://user-images.githubusercontent.com/43877689/170741712-982bca15-8b2f-40c3-ac0a-672ee3d6f90f.png)

2022-05-28 01:03 UTC, smunozmo requested changes
Hi @eudondian, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

- [ ] You have submitted a Pull Request for the second part of the portfolio activity (works and about sections), but in this PR is for the first part (Navigation and Hero sections).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-28 01:16 UTC, smunozmo requested changes
Hi @eudondian, 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

<img src="https://media1.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 01:16 UTC, smunozmo commented on index.html
> +           <section class="headline">
- [ ] You are almost there! However, as the previous reviewer said, it would be better to use a `header` tag for this part.

2022-05-28 01:16 UTC, smunozmo commented on index.html
> +                <li><img src="/Imgs/Victory.svg" alt=""></li>
- [ ] Great job using `li` tags for listings! I would suggest adding `a` tags inside the `li` tags as the previous reviewer said.

2022-05-28 01:40 UTC, eudondian commented
Hello Sebastian,
Thank you for the feedback.
Please, assist me on how to write the code as linters errors says "a"
element not allowed as a child of element "ul".

Thank you

[image: image.png]

On Sat, May 28, 2022 at 2:17 AM Sebastián Muñoz ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @eudondian <https://github.com/eudondian>, 👋
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> Highlights 👏
>
>    - Great work using the right GitHub Flow.
>    - Your README looks professional, well done!
>    - Commits are descriptive, good work.
>    - Linters are working properly, great job!
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
>
> <https://camo.githubusercontent.com/d6579fddc8d090207bae8bed660e0dce450b33c4184427594c35e57690dbefa3/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f7a35634e716246624d544441342f67697068792e676966>
>
> Cheers and Happy coding! 🤓
>
> ✅ Feel free to leave any questions or comments in the PR thread if
> something is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> ⚠️ *Please, do not open a new Pull Request for re-reviews. You should use
> the same Pull Request submitted for the first review, either valid or
> invalid unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/eudondian/Portfolio/pull/1#discussion_r884046314>:
>
> > +           <Section class="header">
>
> +               <Nav>
>
> +                   <a href=""><h3>My Logo</h3></a>
>
> +                   <span class="material-icons">menu</span>
>
> +               </Nav>
>
> +           </Section>
>
> +           <section class="headline">
>
>
>
>    - You are almost there! However, as the previous reviewer said, it
>    would be better to use a header tag for this part.
>
> ------------------------------
>
> In index.html
> <https://github.com/eudondian/Portfolio/pull/1#discussion_r884046462>:
>
> > +                <li><img src="/Imgs/Vector.svg" alt=""></li>
>
> +                <li><img src="/Imgs/linkedin.svg" alt=""></li>
>
> +                <li><img src="/Imgs/M-Vector.svg" alt=""></li>
>
> +                <li><img src="/Imgs/github.svg" alt=""></li>
>
> +                <li><img src="/Imgs/Victory.svg" alt=""></li>
>
>
>
>    - Great job using li tags for listings! I would suggest adding a tags
>    inside the li tags as the previous reviewer said.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eudondian/Portfolio/pull/1#pullrequestreview-988265284>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVSKV2RK4GYQR4RLQY2FDGDVMFXZHANCNFSM5XEIULTQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-28 02:30 UTC, Lucas-Masaba approved these changes
# Hello @eudondian  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- Made changes requested by previous reviewers 👍 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 02:33 UTC, merged