Mob desk popup
eudondian/Portfolio pull request #17
Opened 2022-06-24 07:33 UTC by eudondian

2022-06-24 13:30 UTC, vechicin requested changes
# Hi @eudondian and @krisbobo ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 13:30 UTC, vechicin commented on style.css
> +}
Your pop-up window doesn't follow the template design on the desktop version.

Your design:

<img width="1440" alt="Screen Shot 2022-06-24 at 8 21 47" src="https://user-images.githubusercontent.com/82426682/175544648-ecfadcd9-9da0-4d38-9c32-bd32709bf867.png">

The template design:

<img width="482" alt="Screen Shot 2022-06-24 at 8 22 30" src="https://user-images.githubusercontent.com/82426682/175544772-27abb5ed-7e4b-4138-b258-340f9cebdfa8.png">

Please fix this.

2022-06-24 13:30 UTC, vechicin commented on index.html
> +        </section> -->
Please remove this commented code to keep a cleaner codebase.

2022-06-24 13:30 UTC, vechicin commented on index.html
>      <section id="cards">
The content of this section needs to be dynamically generated.

<img width="1063" alt="Screen Shot 2022-06-24 at 8 25 28" src="https://user-images.githubusercontent.com/82426682/175545292-05caa65c-1801-4ab7-8780-09da0b04c3c1.png">

Please do so.

2022-06-24 13:30 UTC, vechicin commented on script/index.js
> +});
I can only open the modal window once after page reload. Every subsequent attempt at opening a mobile window throws an error in the console. The reason for that is that you are applying an `onclick` attribute directly to the HTML calling a `popup()` method that becomes null after the first click. You should have an array or an object that holds the section information and create a function that opens and closes the modal window for each project.

<img width="1109" alt="Screen Shot 2022-06-24 at 8 29 00" src="https://user-images.githubusercontent.com/82426682/175545913-85f73188-eadc-4c78-87f6-30f4d390a61b.png">

Please fix this.

2022-06-25 22:06 UTC, omarsalem7 approved these changes
Hi @eudondian 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ No linter errors. 
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 22:08 UTC, merged